(DEFINE-CONFIGURATION WEB-BUFFER
  ((DEFAULT-MODES '(EMACS-MODE CERTIFICATE-EXCEPTION-MODE WEB-MODE BASE-MODE))))
(DEFINE-CONFIGURATION WEB-BUFFER
  ((DEFAULT-MODES '(EMACS-MODE CERTIFICATE-EXCEPTION-MODE WEB-MODE BASE-MODE))))
(DEFINE-CONFIGURATION BROWSER
  ((SESSION-RESTORE-PROMPT :never-restore)))
